CALLBACKS = {
    'OnGame': 'OnGameModeInit',
    'OnGameExit': 'OnGameModeExit',
    'IncomingConnection': 'OnIncomingConnection',
    'PlayerJoin': 'OnPlayerConnect',
    'PlayerLeave': 'OnPlayerDisconnect',
    'PlayerFinishedDownloading': 'OnPlayerFinishedDownloading',
    'PlayerChat': 'OnPlayerText',
    'PlayerCommand': 'OnPlayerCommandText',
    'PlayerSpawn': 'OnPlayerSpawn',
    'PlayerDeath': 'OnPlayerDeath',
    'PlayerRequestClass': 'OnPlayerRequestClass',
    'PlayerRequestSpawn': 'OnPlayerRequestSpawn',
    'PlayerEnterVehicle': 'OnPlayerEnterVehicle',
    'PlayerExitVehicle': 'OnPlayerExitVehicle',
    'PlayerStateChange': 'OnPlayerStateChange',
    'PlayerInteriorChange': 'OnPlayerInteriorChange',
    'PlayerKeyChange': 'OnPlayerKeyStateChange',
    'PlayerUpdate': 'OnPlayerUpdate',
    'PlayerStreamIn': 'OnPlayerStreamIn',
    'PlayerStreamOut': 'OnPlayerStreamOut',
    'PlayerPickup': 'OnPlayerPickUpPickup',
    'PlayerEnterCheckpoint': 'OnPlayerEnterCheckpoint',
    'PlayerLeaveCheckpoint': 'OnPlayerLeaveCheckpoint',
    'PlayerEnterRaceCheckpoint': 'OnPlayerEnterRaceCheckpoint',
    'PlayerLeaveRaceCheckpoint': 'OnPlayerLeaveRaceCheckpoint',
    'PlayerClickPlayer': 'OnPlayerClickPlayer',
    'PlayerClickMap': 'OnPlayerClickMap',
    'PlayerClickTextDraw': 'OnPlayerClickTextDraw',
    'PlayerClickPlayerTextDraw': 'OnPlayerClickPlayerTextDraw',
    'PlayerGiveDamage': 'OnPlayerGiveDamage',
    'PlayerTakeDamage': 'OnPlayerTakeDamage',
    'PlayerGiveDamageActor': 'OnPlayerGiveDamageActor',
    'PlayerWeaponShot': 'OnPlayerWeaponShot',
    'PlayerEditObject': 'OnPlayerEditObject',
    'PlayerEditAttachedObject': 'OnPlayerEditAttachedObject',
    'PlayerSelectObject': 'OnPlayerSelectObject',
    'VehicleSpawn': 'OnVehicleSpawn',
    'VehicleDeath': 'OnVehicleDeath',
    'VehicleMod': 'OnVehicleMod',
    'VehiclePaintjob': 'OnVehiclePaintjob',
    'VehicleRespray': 'OnVehicleRespray',
    'VehicleDamage': 'OnVehicleDamageStatusUpdate',
    'VehicleStreamIn': 'OnVehicleStreamIn',
    'VehicleStreamOut': 'OnVehicleStreamOut',
    'VehicleSirenStateChange': 'OnVehicleSirenStateChange',
    'TrailerUpdate': 'OnTrailerUpdate',
    'UnoccupiedVehicleUpdate': 'OnUnoccupiedVehicleUpdate',
    'ActorStreamIn': 'OnActorStreamIn',
    'ActorStreamOut': 'OnActorStreamOut',
    'NPCSpawn': 'OnNPCSpawn',
    'NPCDeath': 'OnNPCDeath',
    'NPCRespawn': 'OnNPCRespawn',
    'NPCTakeDamage': 'OnNPCTakeDamage',
    'DialogResponse': 'OnDialogResponse',
    'RconCommand': 'OnRconCommand',
    'RconLogin': 'OnRconLoginAttempt',
}

CALLBACK_PARAM_COUNT = {
    'OnGameModeInit': 0, 'OnGameModeExit': 0,
    'OnIncomingConnection': 3,
    'OnPlayerConnect': 1, 'OnPlayerDisconnect': 2,
    'OnPlayerFinishedDownloading': 2,
    'OnPlayerText': 2, 'OnPlayerCommandText': 2,
    'OnPlayerSpawn': 1, 'OnPlayerDeath': 3,
    'OnPlayerRequestClass': 2, 'OnPlayerRequestSpawn': 1,
    'OnPlayerEnterVehicle': 3, 'OnPlayerExitVehicle': 2,
    'OnPlayerStateChange': 3,
    'OnPlayerInteriorChange': 3,
    'OnPlayerKeyStateChange': 3,
    'OnPlayerUpdate': 1, 'OnPlayerStreamIn': 2, 'OnPlayerStreamOut': 2,
    'OnPlayerPickUpPickup': 2, 'OnPlayerEnterCheckpoint': 1,
    'OnPlayerLeaveCheckpoint': 1, 'OnPlayerEnterRaceCheckpoint': 1,
    'OnPlayerLeaveRaceCheckpoint': 1, 'OnPlayerClickPlayer': 3,
    'OnPlayerClickMap': 4, 'OnPlayerClickTextDraw': 2,
    'OnPlayerClickPlayerTextDraw': 2,
    'OnPlayerGiveDamage': 5, 'OnPlayerTakeDamage': 5,
    'OnPlayerGiveDamageActor': 5,
    'OnPlayerWeaponShot': 7,
    'OnPlayerEditObject': 8,
    'OnPlayerEditAttachedObject': 11,
    'OnPlayerSelectObject': 6,
    'OnVehicleSpawn': 1, 'OnVehicleDeath': 2,
    'OnVehicleMod': 3, 'OnVehiclePaintjob': 3, 'OnVehicleRespray': 4,
    'OnVehicleDamageStatusUpdate': 2,
    'OnVehicleStreamIn': 2, 'OnVehicleStreamOut': 2,
    'OnVehicleSirenStateChange': 3,
    'OnTrailerUpdate': 2,
    'OnUnoccupiedVehicleUpdate': 7,
    'OnActorStreamIn': 2, 'OnActorStreamOut': 2,
    'OnNPCSpawn': 1, 'OnNPCDeath': 3, 'OnNPCRespawn': 1, 'OnNPCTakeDamage': 4,
    'OnDialogResponse': 5,
    'OnRconCommand': 1, 'OnRconLoginAttempt': 3,
}