# mappings.py

CALLBACKS = {
    'OnGame': 'OnGameModeInit',
    'OnGameExit': 'OnGameModeExit',
    'PlayerJoin': 'OnPlayerConnect',
    'PlayerLeave': 'OnPlayerDisconnect',
    'PlayerChat': 'OnPlayerText',
    'PlayerCommand': 'OnPlayerCommandText',
    'PlayerSpawn': 'OnPlayerSpawn',
    'PlayerDeath': 'OnPlayerDeath',
    'PlayerRequestClass': 'OnPlayerRequestClass',
    'PlayerRequestSpawn': 'OnPlayerRequestSpawn',
    'PlayerEnterVehicle': 'OnPlayerEnterVehicle',
    'PlayerExitVehicle': 'OnPlayerExitVehicle',
    'PlayerStateChange': 'OnPlayerStateChange',
    'PlayerKeyChange': 'OnPlayerKeyStateChange',
    'PlayerUpdate': 'OnPlayerUpdate',
    'PlayerStreamIn': 'OnPlayerStreamIn',
    'PlayerStreamOut': 'OnPlayerStreamOut',
    'PlayerPickup': 'OnPlayerPickUpPickup',
    'PlayerEnterCheckpoint': 'OnPlayerEnterCheckpoint',
    'PlayerLeaveCheckpoint': 'OnPlayerLeaveCheckpoint',
    'PlayerEnterRaceCheckpoint': 'OnPlayerEnterRaceCheckpoint',
    'PlayerLeaveRaceCheckpoint': 'OnPlayerLeaveRaceCheckpoint',
    'PlayerClickPlayer': 'OnPlayerClickPlayer',
    'PlayerClickMap': 'OnPlayerClickMap',
    'PlayerClickTextDraw': 'OnPlayerClickTextDraw',
    'PlayerGiveDamage': 'OnPlayerGiveDamage',
    'PlayerTakeDamage': 'OnPlayerTakeDamage',
    'PlayerWeaponShot': 'OnPlayerWeaponShot',
    'VehicleSpawn': 'OnVehicleSpawn',
    'VehicleDeath': 'OnVehicleDeath',
    'VehicleMod': 'OnVehicleMod',
    'VehiclePaintjob': 'OnVehiclePaintjob',
    'VehicleRespray': 'OnVehicleRespray',
    'VehicleDamage': 'OnVehicleDamageStatusUpdate',
    'VehicleStreamIn': 'OnVehicleStreamIn',
    'VehicleStreamOut': 'OnVehicleStreamOut',
    'DialogResponse': 'OnDialogResponse',
    'RconCommand': 'OnRconCommand',
}


# jumlah parameter expected (warning saja, bukan strict check)
CALLBACK_PARAM_COUNT = {
    'OnGameModeInit': 0,
    'OnGameModeExit': 0,
    'OnPlayerConnect': 1,
    'OnPlayerDisconnect': 2,
    'OnPlayerText': 2,
    'OnPlayerCommandText': 2,
    'OnPlayerSpawn': 1,
    'OnPlayerDeath': 3,
    'OnPlayerRequestClass': 2,
    'OnPlayerRequestSpawn': 1,
    'OnPlayerEnterVehicle': 3,
    'OnPlayerExitVehicle': 2,
    'OnPlayerStateChange': 3,
    'OnPlayerKeyStateChange': 3,
    'OnPlayerUpdate': 1,
    'OnPlayerStreamIn': 2,
    'OnPlayerStreamOut': 2,
    'OnPlayerPickUpPickup': 2,
    'OnPlayerEnterCheckpoint': 1,
    'OnPlayerLeaveCheckpoint': 1,
    'OnPlayerEnterRaceCheckpoint': 1,
    'OnPlayerLeaveRaceCheckpoint': 1,
    'OnPlayerClickPlayer': 3,
    'OnPlayerClickMap': 2,
    'OnPlayerClickTextDraw': 2,
    'OnPlayerGiveDamage': 4,
    'OnPlayerTakeDamage': 4,
    'OnPlayerWeaponShot': 4,
    'OnVehicleSpawn': 1,
    'OnVehicleDeath': 2,
    'OnVehicleMod': 3,
    'OnVehiclePaintjob': 3,
    'OnVehicleRespray': 4,
    'OnVehicleDamageStatusUpdate': 2,
    'OnVehicleStreamIn': 2,
    'OnVehicleStreamOut': 2,
    'OnDialogResponse': 5,
    'OnRconCommand': 1,
}