# natives.py

NATIVES = {
    'GetMoney': dict(pawn='GetPlayerMoney'),
    'GiveMoney': dict(pawn='GivePlayerMoney'),
    'ResetMoney': dict(pawn='ResetPlayerMoney'),
    'GetHealth': dict(pawn='GetPlayerHealth', refs=[1]),
    'SetHealth': dict(pawn='SetPlayerHealth'),
    'GetArmour': dict(pawn='GetPlayerArmour', refs=[1]),
    'SetArmour': dict(pawn='SetPlayerArmour'),
    'GetPos': dict(pawn='GetPlayerPos', refs=[1, 2, 3]),
    'SetPos': dict(pawn='SetPlayerPos'),
    'SetPosFindZ': dict(pawn='SetPlayerPosFindZ'),
    'GetFacingAngle': dict(pawn='GetPlayerFacingAngle', refs=[1]),
    'SetFacingAngle': dict(pawn='SetPlayerFacingAngle'),
    'GetInterior': dict(pawn='GetPlayerInterior'),
    'SetInterior': dict(pawn='SetPlayerInterior'),
    'GetVirtualWorld': dict(pawn='GetPlayerVirtualWorld'),
    'SetVirtualWorld': dict(pawn='SetPlayerVirtualWorld'),
    'GetName': dict(pawn='GetPlayerName', fills_buffer=True),
    'SetName': dict(pawn='SetPlayerName'),
    'GetSkin': dict(pawn='GetPlayerSkin'),
    'SetSkin': dict(pawn='SetPlayerSkin'),
    'GetScore': dict(pawn='GetPlayerScore'),
    'SetScore': dict(pawn='SetPlayerScore'),
    'GetWanted': dict(pawn='GetPlayerWantedLevel'),
    'SetWanted': dict(pawn='SetPlayerWantedLevel'),
    'GetState': dict(pawn='GetPlayerState'),
    'IsConnected': dict(pawn='IsPlayerConnected'),
    'IsInVehicle': dict(pawn='IsPlayerInVehicle'),
    'IsInAnyVehicle': dict(pawn='IsPlayerInAnyVehicle'),
    'IsNPC': dict(pawn='IsPlayerNPC'),
    'IsAdmin': dict(pawn='IsPlayerAdmin'),
    'IsInRange': dict(pawn='IsPlayerInRangeOfPoint'),
    'SetTeam': dict(pawn='SetPlayerTeam'),
    'GetTeam': dict(pawn='GetPlayerTeam'),
    'SetColor': dict(pawn='SetPlayerColor'),
    'GetColor': dict(pawn='GetPlayerColor'),
    'SetControllable': dict(pawn='TogglePlayerControllable'),
    'SetSpectating': dict(pawn='TogglePlayerSpectating'),
    'Kick': dict(pawn='Kick'),
    'Ban': dict(pawn='Ban'),
    'BanEx': dict(pawn='BanEx'),
    'Spawn': dict(pawn='SpawnPlayer'),
    'GiveWeapon': dict(pawn='GivePlayerWeapon'),
    'ResetWeapons': dict(pawn='ResetPlayerWeapons'),
    'GetWeapon': dict(pawn='GetPlayerWeapon'),
    'GetAmmo': dict(pawn='GetPlayerAmmo'),
    'SendAll': dict(pawn='SendClientMessageToAll'),
    'GameText': dict(pawn='GameTextForPlayer'),
    'GameTextAll': dict(pawn='GameTextForAll'),
    'PutInVehicle': dict(pawn='PutPlayerInVehicle'),
    'GetVehicleID': dict(pawn='GetPlayerVehicleID'),
    'GetVehicleSeat': dict(pawn='GetPlayerVehicleSeat'),
    'GetVehiclePos': dict(pawn='GetVehiclePos', refs=[1, 2, 3]),
    'SetVehiclePos': dict(pawn='SetVehiclePos'),
    'GetVehicleHealth': dict(pawn='GetVehicleHealth', refs=[1]),
    'SetVehicleHealth': dict(pawn='SetVehicleHealth'),
    'Repair': dict(pawn='RepairVehicle'),
    'DestroyVehicle': dict(pawn='DestroyVehicle'),
}