NATIVES = {
    'GetMoney': dict(pawn='GetPlayerMoney'),
    'GiveMoney': dict(pawn='GivePlayerMoney'),
    'ResetMoney': dict(pawn='ResetPlayerMoney'),
    'GetHealth': dict(pawn='GetPlayerHealth', refs=[1]),
    'SetHealth': dict(pawn='SetPlayerHealth'),
    'GetArmour': dict(pawn='GetPlayerArmour', refs=[1]),
    'SetArmour': dict(pawn='SetPlayerArmour'),
    'GetPos': dict(pawn='GetPlayerPos', refs=[1, 2, 3]),
    'SetPos': dict(pawn='SetPlayerPos'),
    'SetPosFindZ': dict(pawn='SetPlayerPosFindZ'),
    'GetFacingAngle': dict(pawn='GetPlayerFacingAngle', refs=[1]),
    'SetFacingAngle': dict(pawn='SetPlayerFacingAngle'),
    'GetInterior': dict(pawn='GetPlayerInterior'),
    'SetInterior': dict(pawn='SetPlayerInterior'),
    'GetVirtualWorld': dict(pawn='GetPlayerVirtualWorld'),
    'SetVirtualWorld': dict(pawn='SetPlayerVirtualWorld'),
    'GetName': dict(pawn='GetPlayerName', fills_buffer=True),
    'SetName': dict(pawn='SetPlayerName'),
    'GetIP': dict(pawn='GetPlayerIp', fills_buffer=True),
    'GetPing': dict(pawn='GetPlayerPing'),
    'GetSkin': dict(pawn='GetPlayerSkin'),
    'SetSkin': dict(pawn='SetPlayerSkin'),
    'GetScore': dict(pawn='GetPlayerScore'),
    'SetScore': dict(pawn='SetPlayerScore'),
    'GetWanted': dict(pawn='GetPlayerWantedLevel'),
    'SetWanted': dict(pawn='SetPlayerWantedLevel'),
    'GetState': dict(pawn='GetPlayerState'),
    'GetSpecialAction': dict(pawn='GetPlayerSpecialAction'),
    'SetSpecialAction': dict(pawn='SetPlayerSpecialAction'),
    'GetKeys': dict(pawn='GetPlayerKeys', refs=[1, 2, 3]),
    'IsConnected': dict(pawn='IsPlayerConnected'),
    'IsInVehicle': dict(pawn='IsPlayerInVehicle'),
    'IsInAnyVehicle': dict(pawn='IsPlayerInAnyVehicle'),
    'IsStreamedIn': dict(pawn='IsPlayerStreamedIn'),
    'IsNPC': dict(pawn='IsPlayerNPC'),
    'IsAdmin': dict(pawn='IsPlayerAdmin'),
    'IsInRange': dict(pawn='IsPlayerInRangeOfPoint'),
    'GetDistance': dict(pawn='GetPlayerDistanceFromPoint'),
    'SetTeam': dict(pawn='SetPlayerTeam'),
    'GetTeam': dict(pawn='GetPlayerTeam'),
    'SetColor': dict(pawn='SetPlayerColor'),
    'GetColor': dict(pawn='GetPlayerColor'),
    'SetControllable': dict(pawn='TogglePlayerControllable'),
    'SetSpectating': dict(pawn='TogglePlayerSpectating'),
    'SpectatePlayer': dict(pawn='PlayerSpectatePlayer'),
    'SpectateVehicle': dict(pawn='PlayerSpectateVehicle'),
    'Kick': dict(pawn='Kick'),
    'Ban': dict(pawn='Ban'),
    'BanEx': dict(pawn='BanEx'),
    'Spawn': dict(pawn='SpawnPlayer'),
    'ForceSpawn': dict(pawn='SpawnPlayer'),
    'GiveWeapon': dict(pawn='GivePlayerWeapon'),
    'ResetWeapons': dict(pawn='ResetPlayerWeapons'),
    'GetWeapon': dict(pawn='GetPlayerWeapon'),
    'GetAmmo': dict(pawn='GetPlayerAmmo'),
    'SetAmmo': dict(pawn='SetPlayerAmmo'),
    'SetArmedWeapon': dict(pawn='SetPlayerArmedWeapon'),
    'SendAll': dict(pawn='SendClientMessageToAll'),
    'SendPlayerMsg': dict(pawn='SendPlayerMessageToPlayer'),
    'SendPlayerMsgAll': dict(pawn='SendPlayerMessageToAll'),
    'GameText': dict(pawn='GameTextForPlayer'),
    'GameTextAll': dict(pawn='GameTextForAll'),
    'PlaySound': dict(pawn='PlayerPlaySound'),
    'StopSound': dict(pawn='StopAudioStreamForPlayer'),
    'PlayAudio': dict(pawn='PlayAudioStreamForPlayer'),
    'Animation': dict(pawn='ApplyAnimation'),
    'ClearAnim': dict(pawn='ClearAnimations'),
    'GetAnimIndex': dict(pawn='GetPlayerAnimationIndex'),
    'SetChatBubble': dict(pawn='SetPlayerChatBubble'),
    'SetCamera': dict(pawn='SetPlayerCameraPos'),
    'SetCameraLookAt': dict(pawn='SetPlayerCameraLookAt'),
    'CameraBehind': dict(pawn='SetCameraBehindPlayer'),
    'GetCameraPos': dict(pawn='GetPlayerCameraPos', refs=[1, 2, 3]),
    'ShowDialog': dict(pawn='ShowPlayerDialog'),
    'HideDialog': dict(pawn='HidePlayerDialog'),
    'PutInVehicle': dict(pawn='PutPlayerInVehicle'),
    'RemoveFromVehicle': dict(pawn='RemovePlayerFromVehicle'),
    'GetVehicleID': dict(pawn='GetPlayerVehicleID'),
    'GetVehicleSeat': dict(pawn='GetPlayerVehicleSeat'),
    'CreateVeh': dict(pawn='CreateVehicle'),
    'GetVehiclePos': dict(pawn='GetVehiclePos', refs=[1, 2, 3]),
    'SetVehiclePos': dict(pawn='SetVehiclePos'),
    'GetVehicleHealth': dict(pawn='GetVehicleHealth', refs=[1]),
    'SetVehicleHealth': dict(pawn='SetVehicleHealth'),
    'GetVehicleZAngle': dict(pawn='GetVehicleZAngle', refs=[1]),
    'SetVehicleZAngle': dict(pawn='SetVehicleZAngle'),
    'AddComponent': dict(pawn='AddVehicleComponent'),
    'RemoveComponent': dict(pawn='RemoveVehicleComponent'),
    'Repair': dict(pawn='RepairVehicle'),
    'DestroyVehicle': dict(pawn='DestroyVehicle'),
    'LinkToInterior': dict(pawn='LinkVehicleToInterior'),
}